### ISSUE TITLE
210517_인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#13]
In GitLab by @Jaemin on May 17, 2021, 14:33

# Todo Item

## 과제 수행 인원
AI: @Jaemin 

## 해야할 일
- [x] Deepfashion dataset (category and attribute prediction) vm으로 이동
- [x] 이미지 데이터 전처리 및 train, validation, test로 이미지 카테고리 분류
- [ ] bounding box 설정 (selective search or IoU)
- [ ] model.py 생성
- [ ] train.py 생성

## 참고해야할 사항
- https://jaehyeongan.github.io/2020/04/15/Basic-Object-Detection/
- https://github.com/abhishekrana/DeepFashion

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 17, 2021, 14:33

changed due date to May 17, 2021

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 17, 2021, 14:33

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 17, 2021, 14:34

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 17, 2021, 14:34

changed title from **210517_jamin** to **210517_ja{+e+}min**

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 17, 2021, 14:53

changed title from **210517_{-jaemin-}** to **210517_{+인공지능+}**

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 17, 2021, 16:51

marked the task **Deepfashion dataset (category and attribute prediction) vm으로 이동** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 17, 2021, 16:51

marked the task **이미지 데이터 전처리 및 train, validation, test로 이미지 카테고리 분류** as completed
