### ISSUE TITLE
210517 프론트엔드

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#15]
In GitLab by @Seongmin on May 17, 2021, 14:37

# Todo Item

## 과제 수행 인원
@soojin @Seongmin 

## 해야할 일
- [x] React Tutorial 학습
- [x] React 폴더 구조 및 환경 세팅
- [x] React 페이지 구성 및 공통 컴포넌트 세팅

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 17, 2021, 14:37

changed due date to May 17, 2021

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 17, 2021, 16:13

marked the task **React 폴더 구조 및 환경 세팅** as completed

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 17, 2021, 19:37

marked the task **React 페이지 구성 및 공통 컴포넌트 세팅** as completed

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 17, 2021, 21:42

marked the task **React Tutorial 학습** as completed
