### ISSUE TITLE
210518 프론트엔드

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#16]
In GitLab by @Seongmin on May 18, 2021, 13:18

# Todo Item

## 과제 수행 인원
@Seongmin 

## 해야할 일
- [x] Styled-Component 학습
- [ ] 공통 컴포넌트 완성
- [x] 로그인 화면 구현

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 18, 2021, 13:18

changed due date to May 18, 2021

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 18, 2021, 13:18

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 18, 2021, 17:02

marked the task **Styled-Component 학습** as completed

**Comment by makeitmin** [comment]
In GitLab by @soojin on May 19, 2021, 01:45

marked the task **공통 컴포넌트 완성** as completed

**Comment by makeitmin** [comment]
In GitLab by @soojin on May 19, 2021, 01:45

marked the task **공통 컴포넌트 완성** as incomplete

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 19, 2021, 13:26

marked the task **로그인 화면 구현** as completed
