### ISSUE TITLE
210518_인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#17]
In GitLab by @Jaemin on May 18, 2021, 13:18

# Todo Item

## 과제 수행 인원
인공지능: @Jaemin 

## 해야할 일
- [x]  이미지 데이터 전처리 및 train, validation, test로 이미지 카테고리 분류
    - [x]  bounding box 설정 (selective search or IoU)
        - 문제: bounding box를 설정하는 과정에서 height와 width의 값이 0이 되는 이미지가 존재하여 분류가 되지 않는 문제 발생
            - 해결 방안
                - [https://github.com/abhishekrana/DeepFashion/issues/7](https://github.com/abhishekrana/DeepFashion/issues/7)
            - 추가적으로 1개의 이미지에 대해서 dataset_create.py를 실행해서 검증하는 방법이 가장 좋지만 그러기 위해서 주어진 코드를 리팩토링을 할 필요성이 있음
        - 총 50개의 category에서 1개씩 실행해보면서 crop된 이미지와 iou 값이 잘 설정되었는지 그리고 crop된 이미지가 의상을 잘 crop 했는지 검증해보기
        - selective_search.py에서 selective_search_bbox 함수에서 region_pixels_threshold 값과 selectivesearch.selective_search()의 파라미터 값을 바꿔보면서 crop된 이미지의 변화에 대해서 검증하기
        - 질문: dataset을 create하는 과정에서 iou 값에 대한 threshold를 설정하게 되면 data의 숫자가 많이 적어지게 되지 않을까? iou 값에 대한 threshold를 dataset을 create하는 과정에서 하는 것이 좋을 지, 이미지를 train 시키는 과정에서 설정하면 좋을 지 의문
- [x]  [model.py](http://model.py) 생성 - vgg16 모델 알아보기
- [ ]  [train.py](http://train.py) 생성
- [x] feature/AI branch 만들어서 vm에서 pull 받기

## 참고해야할 사항

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 18, 2021, 13:18

changed due date to May 18, 2021

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 18, 2021, 21:55

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 19, 2021, 13:26

marked the task **이미지 데이터 전처리 및 train, validation, test로 이미지 카테고리 분류** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 19, 2021, 13:26

marked the task **bounding box 설정 (selective search or IoU)** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 19, 2021, 13:26

marked the task **feature/AI branch 만들어서 vm에서 pull 받기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 19, 2021, 13:26

marked the task **[model.py](http://model.py) 생성 - vgg16 모델 알아보기** as completed
