### ISSUE TITLE
210518 백엔드

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#18]
In GitLab by @yjk5309 on May 18, 2021, 13:23

# Todo Item

## 과제 수행 인원
@Serothie @yjk5309 

## 해야할 일
- [x] 서버 개발환경 및 파일 병합
- [x] 로그인 구현 계속
- [x] 캘린더 이미지 CRU 계속

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 18, 2021, 18:49

marked the task **서버 개발환경 및 파일 병합** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 18, 2021, 18:49

marked the task **로그인 구현 계속** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 18, 2021, 18:49

marked the task **캘린더 이미지 CRU 계속** as completed
