### ISSUE TITLE
210520 백엔드

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#30]
In GitLab by @yjk5309 on May 20, 2021, 13:20

# Todo Item

## 과제 수행 인원
@Serothie @yjk5309 

## 해야할 일
- [x] 날씨 API 전처리
- [x] 프론트에서 API를 사용할 수 있도록 문서화
- [x] 사용자 정보를 프론트로 보내는 API
- [x] 친구 추가 로직 구상

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 20, 2021, 16:58

marked the task **사용자 정보를 프론트로 보내는 API** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 21, 2021, 13:02

marked the task **날씨 API 전처리** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 21, 2021, 13:02

marked the task **프론트에서 API를 사용할 수 있도록 문서화** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 21, 2021, 13:02

marked the task **친구 추가 로직 구상** as completed
