### ISSUE TITLE
210520 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#31]
In GitLab by @Jaemin on May 20, 2021, 13:31

# Todo Item

## 과제 수행 인원
인공지능: @Jaemin 

## 해야할 일
- [x] 현재 만든 모델을 epochs 15로 설정해서 CSVLogger, ModelCheckpoint도 callbacks 저정하기
- [x] test 데이터로 evaluate하기
- [x] 간단하게 서빙할 수 있는 파이프라인 구축하기

## 참고해야할 사항
- https://github.com/MorSlomi/DeepFashion/blob/master/DeepFashionModelVGG16.py

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 21, 2021, 02:37

marked the task **현재 만든 모델을 epochs 15로 설정해서 CSVLogger, ModelCheckpoint도 callbacks 저정하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 21, 2021, 02:37

marked the task **test 데이터로 evaluate하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 21, 2021, 02:37

marked the task **간단하게 서빙할 수 있는 파이프라인 구축하기** as completed
