### ISSUE TITLE
210521 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#40]
In GitLab by @Jaemin on May 21, 2021, 13:40

# Todo Item

## 과제 수행 인원
인공지능: @Jaemin 

## 해야할 일
- [x] 코치님 피드백 반영하고 이슈 작성하기
- [ ] flask-server의 modules for app 폴더에 학습한 모델 서빙을 위한 api 구축하기 (Blueprint)
- [x] 데이터 불균형 문제를 해결하기 위한 피드백이 오면 피드백을 반영한 모델 학습하기

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 21, 2021, 13:40

changed due date to May 21, 2021

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 21, 2021, 15:16

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 21, 2021, 15:16

marked the task **코치님 피드백 반영하고 이슈 작성하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 22, 2021, 13:34

marked the task **데이터 불균형 문제를 해결하기 위한 피드백이 오면 피드백을 반영한 모델 학습하기** as completed
