### ISSUE TITLE
210522 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#43]
In GitLab by @Jaemin on May 22, 2021, 13:42

# Todo Item

## 과제 수행 인원
인공지능 : @Jaemin 

## 해야할 일
- [x] 어제 피드백 받은 내용 반영해서 카테고리 축소 후, 모델 학습
- [ ] 학습 결과를 바탕으로 데이터 oversampling or undersampling을 해야한다면 시행
- [x] confusion matrix 그려보기
- [x] tflite 파일로 변환 후, flask-server app에서 classification prediction을 위한 api를 blueprint로 연결
- [ ] 상의와 하의 object detection을 위한 yolo 모델 알아보고, 데이터 셋 라벨링 (시간이 있다면...)

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 22, 2021, 13:42

changed due date to May 22, 2021

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 22, 2021, 15:13

marked the task **어제 피드백 받은 내용 반영해서 카테고리 축소 후, 모델 학습** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 22, 2021, 15:13

marked the task **학습 결과를 바탕으로 데이터 oversampling or undersampling을 해야한다면 시행** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 22, 2021, 15:13

marked the task **학습 결과를 바탕으로 데이터 oversampling or undersampling을 해야한다면 시행** as incomplete

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 22, 2021, 15:13

marked the task **confusion matrix 그려보기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 22, 2021, 19:21

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 22, 2021, 19:21

marked the task **tflite 파일로 변환 후, flask-server app에서 classification prediction을 위한 api를 blueprint로 연결** as completed
