### ISSUE TITLE
210522 백엔드

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#44]
In GitLab by @Serothie on May 22, 2021, 13:52

# Todo Item

## 과제 수행 인원

@Serothie @yjk5309 

## 해야할 일
- [x] 위치정보 동의 저장 처리
- [x] 친구 추가 기능 스토리보드 개발
- [x] FE-BE 간 API 연결 및 조정

## 참고해야할 사항

**Comment by makeitmin** [comment]
In GitLab by @Serothie on May 22, 2021, 13:52

changed due date to May 22, 2021

**Comment by makeitmin** [comment]
In GitLab by @Serothie on May 22, 2021, 13:52

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Serothie on May 22, 2021, 13:52

changed the description

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 22, 2021, 15:27

marked the task **위치정보 동의 저장 처리** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 22, 2021, 17:40

marked the task **친구 추가 기능 API 개발** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 22, 2021, 17:40

marked the task **친구 추가 기능 API 개발** as incomplete

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 22, 2021, 17:41

changed the description

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 22, 2021, 17:41

marked the task **친구 추가 기능 스토리보드 개발** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 22, 2021, 21:56

marked the task **FE-BE 간 API 연결 및 조정** as completed
