### ISSUE TITLE
210526 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#50]
In GitLab by @Jaemin on May 26, 2021, 18:09

# Todo Item

## 과제 수행 인원
인공지능: @Jaemin 

## 해야할 일
- [x] Deepfashion2 데이터 셋으로 학습된 YOLOv3 모델로 object detection
- [x] 기존의 Deepfashion 데이터 셋의 train dataset 부분만 sampling을 통해 데이터 분포 균등하게 맞추기
- [x] 기존의 Deepfashion 데이터 셋의 validation dataset 부분에서 data가 많은 부분만 undersampling 하기
- [x] 앞서 시행한 데이터 셋들을 가지고 모델 학습 및 confusion matrix, classification_report 그려보기
- [ ] classification 모델을 서빙하기 전 먼저 object detection을 한 이미지를 classification 모델이 넣고 예측 결과를 가져오는 api 작성하기
  - [ ] 업로드한 이미지에 대해서 object detection을 한 결과 이미지와 라벨을 사용자에게 확인하는 api 구성
  - [ ] 만약 object detection이 성공한 이미지라면 classification 모델에 object detection된 이미지(cropped)를 넣어서 classification prediction에 대한 top3 카테고리 출력

## 참고해야할 사항
https://github.com/simaiden/Clothing-Detection

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 27, 2021, 13:13

marked the task **Deepfashion2 데이터 셋으로 학습된 YOLOv3 모델로 object detection** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 27, 2021, 13:13

marked the task **기존의 Deepfashion 데이터 셋의 train dataset 부분만 sampling을 통해 데이터 분포 균등하게 맞추기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 27, 2021, 13:13

marked the task **기존의 Deepfashion 데이터 셋의 validation dataset 부분에서 data가 많은 부분만 undersampling 하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 27, 2021, 13:14

marked the task **앞서 시행한 데이터 셋들을 가지고 모델 학습 및 confusion matrix, classification_report 그려보기** as completed
