### ISSUE TITLE
210527 프론트엔드

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#52]
In GitLab by @Seongmin on May 27, 2021, 01:26

# Todo Item

## 과제 수행 인원
@Seongmin @soojin 

## 해야할 일
* [x] 코드 통합 이슈
  - NavBar, Header 컴포넌트 관리
  - Router 관리
* [x] Main 컴포넌트 API 연결

* [ ] 반응형 공부해서 적용시키기

## 참고해야할 사항
* N/A

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 27, 2021, 01:26

changed due date to May 27, 2021

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 27, 2021, 17:11

marked the task **코드 통합 이슈** as completed

**Comment by makeitmin** [comment]
In GitLab by @soojin on May 27, 2021, 17:20

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 28, 2021, 13:20

changed due date to May 28, 2021

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on May 30, 2021, 13:42

marked the task **Main 컴포넌트 API 연결** as completed
