### ISSUE TITLE
210527 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#53]
In GitLab by @Jaemin on May 27, 2021, 13:15

# Todo Item

## 과제 수행 인원
인공지능: @Jaemin 

## 해야할 일
- [ ] classification 모델을 서빙하기 전 먼저 object detection을 한 이미지를 classification 모델애 넣고 예측 결과를 가져오는 api 작성하기
  - [ ] 업로드한 이미지에 대해서 object detection을 한 결과 이미지와 라벨을 사용자에게 확인하는 api 구성
  - [ ] 만약 object detection이 성공한 이미지라면 classification 모델에 object detection된 이미지(cropped)를 넣어서 classification prediction에 대한 top3 카테고리 출력
- [x] 학습을 돌릴 모델에 대해서 코치님께 피드백 받고, 오늘 밤에 학습하기
- [x] 의류 소재 및 의류 색상에 대한 라벨링이 잘 되어있는 데이터 셋 찾아보기

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 27, 2021, 13:16

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 27, 2021, 13:32

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 28, 2021, 14:09

marked the task **학습을 돌릴 모델에 대해서 코치님께 피드백 받고, 오늘 밤에 학습하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 28, 2021, 14:09

marked the task **의류 소재 및 의류 색상에 대한 라벨링이 잘 되어있는 데이터 셋 찾아보기** as completed
