### ISSUE TITLE
210527 백엔드 + α

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#54]
In GitLab by @yjk5309 on May 27, 2021, 13:17

# Todo Item

## 과제 수행 인원
@Serothie @yjk5309 

## 해야할 일
- [x]  몽고엔진 리팩토링 완료시키기(models.py로 도큐먼트, 스키마 관리)
- [x]  프론트 요청에 따른 Calendar.py DB 정보 반환 방식 수정
- [ ]  시간이 되면 Swagger 활용해서 문서화 시도
- [x]  중간 발표 자료 작성

## 참고해야할 사항

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 27, 2021, 13:17

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Serothie on May 27, 2021, 13:22

changed title from **210527 백엔드** to **210527 백엔드{+ + α+}**

**Comment by makeitmin** [comment]
In GitLab by @Serothie on May 27, 2021, 13:22

changed the description

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 27, 2021, 16:03

marked the task **몽고엔진 리팩토링 완료시키기(models.py로 도큐먼트, 스키마 관리)** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 28, 2021, 13:19

marked the task **중간 발표 자료 작성** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on May 28, 2021, 13:19

marked the task **프론트 요청에 따른 Calendar.py DB 정보 반환 방식 수정** as completed
