### ISSUE TITLE
210528 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#57]
In GitLab by @Jaemin on May 28, 2021, 13:50

# Todo Item

## 과제 수행 인원
인공지능 : @Jaemin 

## 해야할 일
- [x] ppt 작성해서 태섭님 드리기
- [ ] 의류 소재 및 색상에 대한 데이터 셋 찾고, 학습하기 위해 데이터 전처리
- [x] Classification and Object Detection API

## 참고해야할 사항

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 28, 2021, 17:40

marked the task **ppt 작성해서 태섭님 드리기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 28, 2021, 17:40

marked the task **Classification and Object Detection API** as completed
