### ISSUE TITLE
210531 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#59]
In GitLab by @Jaemin on May 31, 2021, 15:34

# Todo Item

## 과제 수행 인원
인공지능 : @Jaemin 

## 해야할 일
- [x] ResNet50 모델 api prediction test를 excel에 정리 (Top 3, Top 5)
  - 검토 결과, 원본 데이터 셋의 카테고리 분류를 구체적으로 다시 정리할 필요가 있음
- [x] serving api 수정하기
- [ ] object detection model 경량화
- [x] azure blob storage 알아보기

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on May 31, 2021, 15:34

changed due date to May 31, 2021

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 1, 2021, 24:33

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 1, 2021, 24:34

marked the task **azure blob storage 알아보기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 1, 2021, 24:34

marked the task **serving api 수정하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 1, 2021, 24:34

marked the task **ResNet50 모델 api prediction test를 excel에 정리 (Top 3, Top 5)** as completed
