### ISSUE TITLE
210601 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#62]
In GitLab by @Jaemin on Jun 1, 2021, 16:42

# Todo Item

## 과제 수행 인원
인공지능 : @Jaemin 

## 해야할 일
- [x] 웹 프론트, 백엔드 실행하기 위한 설정 (mongodb)
- [x] 프론트에서 설정한 웹캠을 이용해서 캡쳐한 사진을 classification api로 받아와서, 이미지 파일 decoding 후 저장 (image_base64)
- [x] 프론트에서 설정한 드래그 앤 드랍을 이용해서 업로드한 사진을 classification api로 받아와서, 이미지 파일 decoding 후 저장 (image_base64)
- [x] 캡쳐 또는 업로드한 이미지를 통해 서빙한 모델이 잘 작동하는 지 체크하기
- [x] Deepfashio 원본 데이터 셋 부검하기... (카테고리를 명확하게 나눌 필요가 있음)

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 1, 2021, 16:42

changed due date to June 01, 2021

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 2, 2021, 13:54

marked the task **웹 프론트, 백엔드 실행하기 위한 설정 (mongodb)** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 2, 2021, 13:54

marked the task **프론트에서 설정한 웹캠을 이용해서 캡쳐한 사진을 classification api로 받아와서, 이미지 파일 decoding 후 저장 (image_base64)** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 2, 2021, 13:54

marked the task **프론트에서 설정한 드래그 앤 드랍을 이용해서 업로드한 사진을 classification api로 받아와서, 이미지 파일 decoding 후 저장 (image_base64)** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 2, 2021, 13:54

marked the task **캡쳐 또는 업로드한 이미지를 통해 서빙한 모델이 잘 작동하는 지 체크하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 2, 2021, 13:54

marked the task **Deepfashio 원본 데이터 셋 부검하기... (카테고리를 명확하게 나눌 필요가 있음)** as completed
