### ISSUE TITLE
210602 프론트엔드

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#65]
In GitLab by @Seongmin on Jun 2, 2021, 14:01

# Todo Item

## 과제 수행 인원
@soojin @Seongmin 

## 해야할 일
* [x] 예측 의류 3개 선택 페이지 만들기
* [x] 촬영 매뉴얼 만들기(Camera.js)
* [x] 렌더링 오류 수정

## 참고해야할 사항
* N/A

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on Jun 2, 2021, 14:01

changed due date to June 02, 2021

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on Jun 2, 2021, 17:14

changed due date to June 03, 2021

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on Jun 3, 2021, 22:11

marked the task **촬영 매뉴얼 만들기(Camera.js)** as completed

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on Jun 3, 2021, 22:13

marked the task **렌더링 오류 수정** as completed

**Comment by makeitmin** [comment]
In GitLab by @Seongmin on Jun 5, 2021, 14:51

marked the task **예측 의류 3개 선택 페이지 만들기** as completed
