### ISSUE TITLE
210602 인공지능

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#66]
In GitLab by @Jaemin on Jun 2, 2021, 14:01

# Todo Item

## 과제 수행 인원
인공지능 : @Jaemin 

## 해야할 일
- [x] Deepfashion dataset 카테고리 분류하기
- [x] 분류된 데이터 sampling하기
- [x] 분류된 데이터로 모델 학습하기

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 2, 2021, 14:01

changed due date to June 02, 2021

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 2, 2021, 14:07

changed the description

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 3, 2021, 17:59

marked the task **Deepfashion dataset 카테고리 분류하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 3, 2021, 17:59

marked the task **분류된 데이터 sampling하기** as completed

**Comment by makeitmin** [comment]
In GitLab by @Jaemin on Jun 3, 2021, 17:59

marked the task **분류된 데이터로 모델 학습하기** as completed
