### ISSUE TITLE
210604 백엔드

### ISSUE THREAD

**Issue by makeitmin** [mirror-look/mirror-look-origin#69]
In GitLab by @yjk5309 on Jun 4, 2021, 13:38

# Todo Item

## 과제 수행 인원
@yjk5309 @Serothie 

## 해야할 일
- [x] 날씨 기반 추천 함수, api 연결
- [x] 날씨 정보 api에서 기온 보내주는 방식으로 수정, 아이콘 추가
- [x] 세탁 기반 추천 함수, api 연결
---
- [x] 캘린더 create 부분 논의    
사진 촬영 -> 프론트에서 결과값 보내주면 recommend.py에서 결과 리턴    
프론트에서 저장하기 누르면 -> 원래 경로를 캘린더에 저장시키기(유저아이디, 경로, 날짜)

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on Jun 4, 2021, 14:37

changed the description

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on Jun 4, 2021, 16:08

marked the task **날씨 정보 api에서 기온 보내주는 방식으로 수정, 아이콘 추가** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on Jun 4, 2021, 17:14

changed the description

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on Jun 4, 2021, 17:21

changed the description

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on Jun 5, 2021, 23:11

changed the description

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on Jun 5, 2021, 23:11

marked the task **날씨 기반 추천 함수, api 연결** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on Jun 5, 2021, 23:11

marked the task **캘린더 create 부분 논의** as completed

**Comment by makeitmin** [comment]
In GitLab by @yjk5309 on Jun 5, 2021, 23:11

marked the task **세탁 기반 추천 함수, api 연결** as completed
